services:

  pythonapp:
    image: pythonapp
    build:
      context: .
      dockerfile: ./dockerfile
    depends_on:
      - neo4j
    networks:
      - default

  neo4j:
    image: neo4j:latest
    platform: linux/amd64
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_data:/var/lib/neo4j/import
      - neo4j_data:/plugins
    networks:
      - default
  
  dbpostgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: UserTest@Gmail.tec.cr
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 5050:80
  
  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - pyspark-data:/notebooks:/home/jovyan/work
    networks:
      - default

volumes:
  neo4j_data:
  neo4j_logs:
  db-data:
  pyspark-data:

networks:
  default:
    driver: bridge