services:
  neo4j:
    image: neo4j:latest
    platform: linux/amd64
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins
      - ./csv:/var/lib/neo4j/import/csv
  
  dbpostgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: UserTest@Gmail.tec.cr
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 5050:80
  dbmongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  neo4j_data:
  neo4j_logs:
  db-data:

networks:
  default:
    driver: bridge